const actionTypes = {
  GET_ALL_CONTACTS_SUCCESS: 'GET_ALL_CONTACTS_SUCCESS',
  GET_ALL_CONTACTS_FAILURE: 'GET_ALL_CONTACTS_FAILURE',
  ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
  ADD_CONTACT_FAILURE: 'ADD_CONTACT_FAILURE',
  DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
  DELETE_CONTACT_FAILURE: 'DELETE_CONTACT_FAILURE',
  FILTER_CONTACTS: 'FILTER_CONTACTS',
  SWITCH_THEME: 'SWITCH_THEME',
  SET_LOADING_TRUE: 'SET_LOADING_TRUE',
  SET_LOADING_FALSE: 'SET_LOADING_FALSE',
};

export default actionTypes;
